"""rename address

Revision ID: 33538da779f0
Revises: e02a8e5a8742
Create Date: 2025-03-27 11:32:03.084631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33538da779f0'
down_revision = 'e02a8e5a8742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###